### ISSUE TITLE
Issues with JNA 4 (was: Time fields don't work, always 0)

### ISSUE THREAD

**Issue by rkfg** [EtiennePerot/fuse-jna#28]
I did a little investigation and it seems that internal binary structures are different for i686 and x86_64. So I'm on amd64 (x86_64) and no matter what ctime, mtime or atime I set with setAllTimesMillis or just mtime(somenumber), it still returns this:
Access: 1970-01-01 03:00:00.000000000 +0300
Modify: 1970-01-01 03:00:00.000000000 +0300
Change: 1970-01-01 03:00:00.000000000 +0300
 Birth: -

Zero, in other words. Other fields work fine except Inode which always shows 31 or 16 for some reason. I set it to 100 for example: stat.ino(100);
But it's 31 or 16 anyway. Maybe it has more distinct values, I only observed these two which change randomly after the program restart. I have fine file/directory mode, size, can set blocks value and uid/gid but time values are completely broken. Inode doesn't concern me much but it would be handy to set it to my internal inode number, too. I'm not familiar with JNA so can't help it. What also suggests it's a fuse-jna error and not mine is that examples also has the same issue. I see that they don't explicitly set the time but there are defaults here in FuseFilesystem.java:

wrapper.setMode(NodeType.DIRECTORY).setAllTimesMillis(System.currentTimeMillis()).nlink(1).uid(FuseJna.getUid()).gid(FuseJna.getGid());

So it should be the current date and time but it's 1 Jan 1970 everywhere. As I can see, it's the same for i686 platform.

**Comment by tbutter** [comment]
I see the same problem with 4.0.0, but it works fine with 4.1.0.

**Comment by tbutter** [comment]
I think that was the fix: https://github.com/twall/jna/commit/95526ab8231ef630fab944a5bec3bfed27009d45
