### ISSUE TITLE
Detecting closure on a file upload

### ISSUE THREAD

**Issue by spinkb** [EtiennePerot/fuse-jna#47]
I've implemented a full fs now.  Happy with things so far.

On a download, or all t he massive number of read calls being made, I can cache a stream and keep reading from it with possibly some jumping around in it and so on depending on the chunk being requested.  But performance is OK.  I can discard my stream when the end of file is hit, or the stream stops being accessed after a while.

However, on a write...how can I detect the copy is "complete"?

Isn't there something similar to a "close"?  I went through the implemented classes and nothing jumped out at me as being a "close" type operation...  For my fs, its an expensive event to start, and stop.  So i need to keep my stream open, and jump around in it if necessary.  But I can't reasonably open and close it...  Any guidance there?

Is there a better place for questions like this?

**Comment by EtiennePerot** [comment]
You're looking for `release` (http://fuse.sourceforge.net/doxygen/structfuse__operations.html#abac8718cdfc1ee273a44831a27393419) or maybe `flush` (http://fuse.sourceforge.net/doxygen/structfuse__operations.html#ad4ec9c309072a92dd82ddb20efa4ab14).

**Comment by spinkb** [comment]
Both are being called, which is excellent!  The release did exactly what i was needing.  Performance is really not too bad.  152MByte/sec on read and write for a 1GB file.  I can live with that.  All of this is translating over to a webserver.  Was doing this with a JLan server and translating via SMB.  Quite pleased so far.  Thanks!

**Comment by spinkb** [comment]
And sorry...one more update.  I turned off logging and got 200MByte/sec read and write.
(SSD drive native is about 500MByte/sec)
So the JNA isn't really causing much slowness... :)
