### ISSUE TITLE
Help: starting hellofs failure

### ISSUE THREAD

**Issue by davidebz** [EtiennePerot/fuse-jna#49]
davide@davide-C7:/tmp$ fuse-jna/examples/hellofs.sh ~/hellofs

FAILURE: Build failed with an exception.

* Where:
Build file '/tmp/fuse-jna/build.gradle' line: 35

* What went wrong:
A problem occurred evaluating root project 'fuse-jna'.
> Could not find property 'MavenPublication' on Publication set.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 7.953 secs
davide@davide-C7:/tmp$ gradle --version

------------------------------------------------------------
Gradle 1.4
------------------------------------------------------------

Gradle build time: Monday, September 9, 2013 8:44:25 PM UTC
Groovy: 1.8.6
Ant: Apache Ant(TM) version 1.9.3 compiled on April 8 2014
Ivy: non official version
JVM: 1.7.0_75 (Oracle Corporation 24.75-b04)
OS: Linux 3.13.0-49-generic amd64

**Comment by EtiennePerot** [comment]
The build works for me on Gradle 1.7. You could upgrade Gradle, or you could just remove the whole `publishing` block if you don't need it. The rest is enough to build the libs and the jar.

**Comment by EtiennePerot** [comment]
The build works for me on Gradle 1.7. You could upgrade Gradle, or you could just remove the whole `publishing` block if you don't need it. The rest is enough to build the libs and the jar.
