### ISSUE TITLE
JavaFS -- a port of fuse-jna to JNR

### ISSUE THREAD

**Issue by pron** [EtiennePerot/fuse-jna#54]
Hi!
Just wanted to let you know that I've ported fuse-jna to JNR, and changed the API so that instead of having a new FUSE API, you just use the standard JDK's `FileSystem` and mount it.

The project is [here](https://github.com/puniverse/javafs), and you're welcome to copy back whatever pieces you want.

**Comment by EtiennePerot** [comment]
This is very cool. I don't think it'd be a good idea to merge things back into fuse-jna because it would go contrary to the project's title, and the change in the library user API would probably not be desirable. However I'll certainly link to this from the README file.

**Comment by EtiennePerot** [comment]
Done in 20c8118.
