### ISSUE TITLE
hi,i am learning use fuse-jna do something,but i meet some trouble.

### ISSUE THREAD

**Issue by wintonBy** [EtiennePerot/fuse-jna#55]
i use the shell scripts to make the program run,but it doesn't work.it as follows:
root@zww-v-m:/home/zww/Downloads/fuse-jna/examples# mkdir ~/hellofs
root@zww-v-m:/home/zww/Downloads/fuse-jna/examples# ./hellofs.sh ~/hellofs
: No such file or directory

**Comment by EtiennePerot** [comment]
Can you add `set -x` on line 2 of `hellofs.sh` and `run.sh` to see what it's doing and where it's failing?

**Comment by wintonBy** [comment]
@EtiennePerot  hi,it seems has no effect.
root@zww-v-m:/home/zww/Downloads/fuse-jna/examples# ls
groovyfs.sh  hellofs.sh  memoryfs.sh  run.sh  test  xattrexamplefs.sh
root@zww-v-m:/home/zww/Downloads/fuse-jna/examples# ./hellofs.sh -x ~/hellofs
: No such file or directory
root@zww-v-m:/home/zww/Downloads/fuse-jna/examples#

**Comment by EtiennePerot** [comment]
No, I meant add `set -x` to the files themselves, not as arguments.

For example, in `hellofs.sh`:

```bash
#!/usr/bin/env bash
set -x
cd "`dirname "$0"`"
./run.sh net.fusejna.examples.HelloFS "$@"
```

**Comment by wintonBy** [comment]
@EtiennePerot thank you.but i did some changes as you say,but has not any effect.as follows:

root@zww-v-m:/home/zww/Downloads/fuse-jna/examples# cat hellofs.sh 
#!/usr/bin/env bash

set -x
cd "`dirname "$0"`"
./run.sh net.fusejna.examples.HelloFS "$@"
root@zww-v-m:/home/zww/Downloads/fuse-jna/examples# ./hellofs.sh ~/hellofs
: No such file or directory
root@zww-v-m:/home/zww/Downloads/fuse-jna/examples#

**Comment by wintonBy** [comment]
@EtiennePerot  i also add on run.sh file ,but it's also does not work

**Comment by EtiennePerot** [comment]
That's pretty weird... Do you have bash installed? Does running with `bash hellofs.sh` work?

You could always just try running what the `hellofs.sh` really runs, but manually:

```shell
$ cd ~/Downloads/fuse-jna
$ GRADLE_USER_HOME=gradle gradle uberJar
$ java -cp build/libs/\* net.fusejna.examples.HelloFS ~/hellofs
```

**Comment by wintonBy** [comment]
$GRADLE_USER_HOME=gradle gradle uberJar
run this command ,it says apt-get install gradle. now i am installing it.is it the reason?

**Comment by EtiennePerot** [comment]
The error message is so non-descript that it's hard to say. The script does check if gradle is installed and tells you to install it if it isn't, but it sounds like it's not even getting to that point. Anyway, yes, install gradle.

**Comment by wintonBy** [comment]
root@zww-v-m:/home/zww/Downloads/fuse-jna# GRADLE_USER_HOME=gradle gradle uberJar

FAILURE: Build failed with an exception.

* Where:
Build file '/home/zww/Downloads/fuse-jna/build.gradle' line: 35

* What went wrong:
A problem occurred evaluating root project 'fuse-jna'.
> Could not find property 'MavenPublication' on Publication set.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 3.746 secs
@EtiennePerot  hi,it seems something is error.

**Comment by wintonBy** [comment]
java -cp build/libs/\* net.fusejna.examples.HelloFS ~/hellofs
Error: Could not find or load main class net.fusejna.examples.HelloFS
root@zww-v-m:/home/zww/Downloads/fuse-jna# 
@EtiennePerot  could not find main class?

**Comment by EtiennePerot** [comment]
It can't find the main class because the build failed, so there's nothing in `build/libs/*`. It will work if the gradle build succeeds. It's probably a gradle version difference? It works for me:

```shell
$ gradle uberJar                                                                                                                          [127]
Download http://repo1.maven.org/maven2/net/java/dev/jna/jna/4.1.0/jna-4.1.0.pom
Download http://repo1.maven.org/maven2/org/codehaus/groovy/groovy-all/2.1.5/groovy-all-2.1.5.pom
Download http://repo1.maven.org/maven2/net/java/dev/jna/jna/4.1.0/jna-4.1.0.jar
Download http://repo1.maven.org/maven2/org/codehaus/groovy/groovy-all/2.1.5/groovy-all-2.1.5.jar
:compileJava
:compileGroovy
:processResources UP-TO-DATE
:classes
:uberJar

BUILD SUCCESSFUL

Total time: 1 mins 6.261 secs
```

Gradle version 1.7 (`gradle --version`).

**Comment by wintonBy** [comment]
root@zww-v-m:/home/zww/Downloads/fuse-jna# gradle -version

------------------------------------------------------------
Gradle 1.4
------------------------------------------------------------

Gradle build time: Monday, September 9, 2013 8:44:25 PM UTC
Groovy: 1.8.6
Ant: Apache Ant(TM) version 1.9.3 compiled on April 8 2014
Ivy: non official version
JVM: 1.7.0_79 (Oracle Corporation 24.79-b02)
OS: Linux 3.13.0-24-generic amd64

root@zww-v-m:/home/zww/Downloads/fuse-jna# 
@EtiennePerot  my gradle is low version

**Comment by EtiennePerot** [comment]
Well, you could either upgrade Gradle, or you can just edit `build.gradle` and remove the whole `publishing` block from it. It should still be able to build the libs, which is all you need to run the examples.

**Comment by wintonBy** [comment]
zww@zww-v-m:fuse-jna$ gradle uberJar

FAILURE: Build failed with an exception.

* Where:
Build file '/home/zww/Downloads/fuse-jna/build.gradle' line: 24

* What went wrong:
Could not resolve all dependencies for configuration ':runtime'.
> Could not resolve net.java.dev.jna:jna:4.1.0.
  Required by:
      fuse-jna:fuse-jna:1.0.3
   > Could not resolve net.java.dev.jna:jna:4.1.0.
      > Could not get resource 'https://repo1.maven.org/maven2/net/java/dev/jna/jna/4.1.0/jna-4.1.0.pom'.
         > Could not GET 'https://repo1.maven.org/maven2/net/java/dev/jna/jna/4.1.0/jna-4.1.0.pom'.
            > peer not authenticated
> Could not resolve org.codehaus.groovy:groovy-all:2.1.5.
  Required by:
      fuse-jna:fuse-jna:1.0.3
   > Could not resolve org.codehaus.groovy:groovy-all:2.1.5.
      > Could not get resource 'https://repo1.maven.org/maven2/org/codehaus/groovy/groovy-all/2.1.5/groovy-all-2.1.5.pom'.
         > Could not GET 'https://repo1.maven.org/maven2/org/codehaus/groovy/groovy-all/2.1.5/groovy-all-2.1.5.pom'.
            > peer not authenticated

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 2 mins 9.785 secs
zww@zww-v-m:fuse-jna$ 
@EtiennePerot  I update the gradle to version2.6,but meet network problem.

**Comment by wintonBy** [comment]
zww@zww-v-m:fuse-jna$ GRADLE_USER_HOME=gradle gradle uberJar

FAILURE: Build failed with an exception.

* What went wrong:
Could not create service of type ScriptPluginFactory using BuildScopeServices.createScriptObjectConfigurerFactory().

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
zww@zww-v-m:fuse-jna$ 
@EtiennePerot  i run this command,but it doet not work?what should i do?

**Comment by EtiennePerot** [comment]
> Could not GET 'https://repo1.maven.org/maven2/net/java/dev/jna/jna/4.1.0/jna-4.1.0.pom'.
> peer not authenticated

It is saying that it cannot download the dependencies automatically. Can you access that URL manually? Do you need to use special proxy settings? Is the HTTPS handshake failing? Do you have your system clock set correctly?

**Comment by wintonBy** [comment]
Because my location at China,so some foreign website is not available for me. are there other way to load lib？

**Comment by EtiennePerot** [comment]
Hmm, that doesn't make things easy. You can't use `gradle` to automatically get and build the `jna` dependency then. Instead, you will have to manually download JNA from here: https://github.com/java-native-access/jna See if you can download the .jar's linked in the README file. Otherwise you can `git clone` the repository. You'll need to figure out how to build a jna.jar file yourself (or maybe ask for help on their GitHub issues list). Once you have `jna.jar` compiled, you can use it in the `java` classpath with

```shell
$ java  -cp 'path/to/jna.jar:build/libs/*' net.fusejna.examples.HelloFS ~/hellofs
```

This sets the classpath (`-cp`) to be from both `path/to/jna.jar` (that you compiled manually) and to `build/libs/*` (all the libs built by gradle).

**Comment by wintonBy** [comment]
@EtiennePerot  hi,I had solved the problem,when i run the shell scripts,because the file format is different,so some trouble appear.
So i use the tool dos2unix to format these shell,and then it is correct.
In the end ,thank you for you cost your time for my problem.

**Comment by EtiennePerot** [comment]
Hmm, all shell files are already using unix linebreaks though. One reason they might not be on your end is if your git client is set to convert them to Windows-style linebreaks automatically. See https://help.github.com/articles/dealing-with-line-endings/

Have you been able to build jna and run the example filesystems?

**Comment by wintonBy** [comment]
yes ,i use git client is windows version. i had build the hello filesystems. now i am try to understand how to code a filesystem by my mean.

**Comment by EtiennePerot** [comment]
This won't work on Windows though, right? The fuse library hasn't been ported to Windows, as far as I know. It only works on Linux, Mac OS X, etc.

**Comment by wintonBy** [comment]
@EtiennePerot  yes ,beacause  my ubuntu is virtual machine,so i usually use windows machine download code and then copy to virtual machine.

**Comment by EtiennePerot** [comment]
Alright. Good luck with writing your filesystem!

**Comment by wintonBy** [comment]
@EtiennePerot  ^-^hah,thank you very much. Could you give me your e-mail address? i think i will need your help .

**Comment by EtiennePerot** [comment]
You can get my email address from my [personal website](https://perot.me/about).

**Comment by wintonBy** [comment]
thank you
