### ISSUE TITLE
Callback 'getattr' is called with non-existing path

### ISSUE THREAD

**Issue by zxkane** [EtiennePerot/fuse-jna#56]
I am using `fuse-jna` library to create a custom FS. When debugging my code, the callback `readdir` was called firstly when `cd` or `ls` a folder. It works fine. In my `readdir` implementation, some files and folder in  that dir path were found, for example,

```
/js
/css
/images
```
However the callback `getattr` were called many times for known(in above list) and **unknown** path(at least they were not returned by the callback `readdir`). 

For example, I did see below path in `getattr` callback,

```
/.git  on both Linux and Mac OSX
/objects on Linux
/._. on MacOSX
/.DS_Store on Mac OSX
```

Do you have any idea why callback `getattr` were called with above non-existing path? They are annoying and might impact the performance.

**Comment by centic9** [comment]
I believe these are accesses done by the operating system which probes for "hidden" stuff that is used for some operating system specific functionality, e.g. caches, meta-data, trash-can, ...

I saw similar accesses in [my project](https://github.com/centic9/jgitfs) which uses fuse-jna and there I ignored those that I encountered, see [IGNORED_DIRS](https://github.com/centic9/JGitFS/blob/master/src/main/java/org/dstadler/jgitfs/JGitFilesystem.java#L70)

**Comment by zxkane** [comment]
@centic9 Thanks for your explanation. Your project JGitFS really inspired me a lot when I am writing [my project](https://github.com/videome/AliyunOSSFS).

**Comment by EtiennePerot** [comment]
Yes, those are indeed just probes by your operating system, file manager, and whatever you have running on your machine. They do that to every filesystem, and they all have to handle that.
